/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_actna8l0qc_termmeta` VALUES
(1,16,"thumbnail_id","18"),
(2,16,"product_count_product_cat","4"),
(3,17,"thumbnail_id","20"),
(4,17,"product_count_product_cat","4"),
(5,18,"thumbnail_id","19"),
(6,18,"product_count_product_cat","4"),
(7,64,"order","0"),
(8,65,"order","0"),
(9,66,"order","0"),
(10,67,"order","0"),
(11,68,"order","0"),
(12,69,"order","0"),
(13,70,"order","0"),
(14,71,"order","0"),
(15,72,"order","0"),
(16,73,"order","0"),
(17,74,"order","0"),
(18,75,"order","0"),
(19,76,"order","0"),
(20,77,"order","0"),
(21,78,"order","0"),
(22,64,"product_count_product_cat","27"),
(23,66,"product_count_product_cat","16"),
(24,71,"product_count_product_cat","4"),
(25,72,"product_count_product_cat","3"),
(26,78,"product_count_product_cat","3"),
(27,76,"product_count_product_cat","4"),
(28,70,"product_count_product_cat","5"),
(29,75,"product_count_product_cat","6"),
(30,74,"product_count_product_cat","3"),
(31,69,"product_count_product_cat","9"),
(32,77,"product_count_product_cat","5"),
(33,73,"product_count_product_cat","11"),
(34,65,"product_count_product_cat","4"),
(35,68,"product_count_product_cat","2"),
(36,67,"product_count_product_cat","3"),
(37,48,"product_count_product_tag","2"),
(38,47,"product_count_product_tag","1"),
(39,59,"product_count_product_tag","1"),
(40,56,"product_count_product_tag","1"),
(41,58,"product_count_product_tag","2"),
(42,55,"product_count_product_tag","1"),
(43,49,"product_count_product_tag","1"),
(44,54,"product_count_product_tag","1"),
(45,50,"product_count_product_tag","1"),
(46,53,"product_count_product_tag","1"),
(47,63,"product_count_product_tag","1"),
(48,51,"product_count_product_tag","1"),
(49,57,"product_count_product_tag","1"),
(50,44,"product_count_product_tag","1"),
(51,43,"product_count_product_tag","1"),
(52,46,"product_count_product_tag","2"),
(53,62,"product_count_product_tag","1"),
(54,45,"product_count_product_tag","2"),
(55,60,"product_count_product_tag","2"),
(56,52,"product_count_product_tag","1"),
(57,61,"product_count_product_tag","1"),
(59,91,"vendor_data","a:12:{s:5:\"notes\";s:0:\"\";s:4:\"logo\";s:4:\"3108\";s:7:\"profile\";s:697:\"Vi på World Class står för hälsa och träning i världsklass.\r\nFör oss betyder hälsa att vi vill hjälpa våra medlemmar att bygga en ny livsstil, träna och befästa en ny vana för livet.  Vi står för långsiktighet, prestigelöshet, och mer innehåll än yta.  Vi tror på livslång hälsa genom människors potential tillsammans med en allsidig träning. Vi tror att de flesta människor kan klara allt bara man tränar på det tillräckligt mycket. Vi inom World Class vill hjälpa våra medlemmar att nå mål som de inte trodde var möjliga – vi vet hur man gör för att lyckas.\r\nVi har träning för årets alla årstider, inomhus och utomhus – vi har träning i världsklass!\";s:5:\"email\";s:24:\"support@getguineapig.com\";s:10:\"commission\";s:0:\"\";s:15:\"commission_type\";s:10:\"percentage\";s:6:\"paypal\";s:0:\"\";s:8:\"timezone\";s:5:\"UTC+0\";s:15:\"enable_bookings\";s:2:\"no\";s:20:\"per_product_shipping\";s:2:\"no\";s:14:\"instant_payout\";s:2:\"no\";s:6:\"admins\";a:0:{}}"),
(60,92,"vendor_data","a:12:{s:5:\"notes\";s:0:\"\";s:4:\"logo\";s:4:\"3119\";s:7:\"profile\";s:1997:\"Bruce ett träningsmedlemskap där man kan träna på flera olika ställen i ett och samma medlemskap. Vi samarbetar i dagsläget med ca. 250 studios i Stockholm, Uppsala och Göteborg. Lanserar Malmö under våren 2018 (se vilka här: https://www.brucepass.com/studios ) \r\n\r\n<strong>Varför bli Brucepartner? </strong>\r\n\r\nGenom BRUCE når ni en bredare målgrupp, får bra exponering och gratis marknadsföring. Det är ett samarbete där vi utgår från era behov och oavsett vilket skede ni ligger i kan vi hjälpa till. Exempelvis kan vi fylla upp klasser som är svåra att fylla själva, får fler personer att hitta till studion/träningsanläggningen, hjälpa till under event och marknadsföra resor, workshops och dylikt. \r\n\r\nVårt mål är att ni som studiopartner ska tjäna lika mycket på Bruce-medlemmar som på era egna medlemmar. Vår målgrupp är de som vill ha en stor bredd i sin träning, som gillar att göra mycket. Personer som vill kunna träna både nära hemmet och jobbet. \r\n\r\nHur fungerar det i praktiken? \r\nVi träffar eller pratar med alla partners först för att se om vi är en match. Vi tänker långsiktigt och det är viktigt att det känns rätt och inte finns några frågetecken kring samarbetet innan vi kör igång. \r\n\r\nTillsammans tittar vi på vilket utbud ni har, vilka klasser ni skulle kunna tänka er att fylla upp och vilka tider som ni har färre antal besökare. Om möjligt så API-kopplar vi också (dvs. vårt bokningssystem pratar med ert. Bruce-bokningarna hamnar då per automatik i ert eget system).\r\n\r\nOm allt känns bra så testar och kör vi och i slutet på månaden får ni en rapport utskickad som visar hur många som tränat hos er och hur mycket pengar det har genererat. Pengarna sätts sedan in på ert BG/PG – en bokföringspost och minimalt med administration.\r\n\r\nFyll i detta formulär för att komma igång.\r\n\r\nAlternativ ring eller mejla mig så får du mer information. \r\n\r\nMail: lizen@brucepass.com\r\nTel: +46722075720 \";s:5:\"email\";s:24:\"support@getguineapig.com\";s:10:\"commission\";s:0:\"\";s:15:\"commission_type\";s:10:\"percentage\";s:6:\"paypal\";s:0:\"\";s:8:\"timezone\";s:5:\"UTC+0\";s:15:\"enable_bookings\";s:2:\"no\";s:20:\"per_product_shipping\";s:2:\"no\";s:14:\"instant_payout\";s:2:\"no\";s:6:\"admins\";a:0:{}}"),
(61,15,"product_count_product_cat","5"),
(62,95,"thumbnail_id","3108");
